version: v2
name: geaux-tipi
services:
  name: tipi
  run: docker-compose up -d
  type: web
  instances: 1
  cpuCores: 0.26
  ramMegabytes: 1300
  terminationGracePeriodSeconds: 30
  port: 8080
  sleep: false
  build:
    context: ./
    method: docker
    dockerfile: ./Dockerfile
  env:
    key: DOCKER_USERNAME
    value: wickedsploit
    key: DOCKER_PASSWORD
    value: Noagenda32@@!?!?
    key: ADMIN_EMAIL
    value: support@geauxspecialist.com
autoRollback:
  enabled: false
